server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devcycle?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: devcycle.official@gmail.com
    password: ooeojcpjsxooudyg
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

logging:
  level:
    root: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa